services:

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    environment:
      - CLICKHOUSE_USER=user
      - CLICKHOUSE_PASSWORD=pass
    ports:
      - "8123:8123"   # HTTP API
      - "9000:9000"   # Native protocol
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
